### ISSUE TITLE
Bypass the Version too old roadblock

### ISSUE THREAD

**Issue by VittGam** [jaysh/xposed-whatsapp#12]
Hi,

I would like to keep an old WA version on my phone, for personal reasons (mainly because I don't like having any of Facebook Inc. software on my devices, and because I don't like the new style changes imposed to WA users by them.)

Unfortunately, today the old WA version I was using got blocked, with a nag screen saying that I would be forced to download and install their new version on my phone in order to continue using WA. This is completely unacceptable for me.

I know I would theoretically be exposed to security issues this way, but has WA ever fixed the fact that privacy is non-existant with their software? (Starting by the fact that my mobile number is sent in clear with almost all of the connection attempts...) So I'm conscious I would continue to use a piece of software that's after all insecure, so I would just avoid using it for sensitive conversations, as I've ever done. But unfortunately it's the social standard for communicating on the phone... So I need to continue using it. :/

So, here comes the real question. Would it be theoretically and/or practically possible to bypass this forced limitation with the Xposed framework? Has anyone tried this before?

Thank you very much for your help! :)
Vittorio G

**Comment by ekardon** [comment]
This does work with none of the WA versions. Please update or remove it from the store.
Thanks

**Comment by VittGam** [comment]
@ekardon I personally stopped trying to workaround a broken-by-design app and switched to a different messaging app.

I think that this issue can be closed as of now...

**Comment by nicolabeghin** [comment]
Interesting thread. Do you think it would be possibile to change the versionCode of whatsapp apk in order to get around this?
